#	$OpenBSD: Makefile,v 1.6 2003/03/02 03:27:24 brad Exp $

# preserve order: 'miniroot' depends on 'bsd.rd', 'cdfs' depends on 'miniroot'
SUBDIR+= ramdisk ramdiskB bsd.rd miniroot cdfs

.include <bsd.subdir.mk>
