#	$OpenBSD: Makefile,v 1.5 2001/11/07 07:45:34 deraadt Exp $

# preserve order: 'miniroot' depends on 'bsd.rd', 'cdfs' depends on 'miniroot'
SUBDIR+= ramdisk bsd.rd miniroot cdfs # ramdiskB

.include <bsd.subdir.mk>
