# $OpenBSD: Makefile,v 1.2 1996/06/23 14:30:20 deraadt Exp $
# $NetBSD: Makefile,v 1.1.1.1.6.1 1996/06/28 17:42:49 jtc Exp $
# edlabel (Edit Disk LABEL)

PROG=	edlabel
NOMAN=
CFLAGS += -Wall
LDADD  += -lutil

all: ${PROG}

.include <bsd.prog.mk>
