#	$OpenBSD: Makefile,v 1.6 2003/06/11 18:50:26 drahn Exp $
#	from: @(#)Makefile	5.1 (Berkeley) 2/12/91

# TODO mpcpcibr isabr
MAN=	autoconf.4 intro.4 mem.4
MLINKS= mem.4 kmem.4

MANSUBDIR=pegasos

.include <bsd.prog.mk>
