# $OpenBSD: Makefile,v 1.1 2013/11/10 19:26:31 schwarze Exp $

REGRESS_TARGETS = nocombine utf8only combine
SKIP_ASCII = utf8only combine
UTF8_TARGETS = nocombine utf8only combine

.include <bsd.regress.mk>
