#	$OpenBSD: Makefile,v 1.2 1994/11/17 08:28:17 jtc Exp $
#	$NetBSD: Makefile,v 1.2 1994/11/17 08:28:17 jtc Exp $

PROG=	retest
SRCS=	regexp.c retest.c
.PATH:	${.CURDIR}/..
NOMAN=	noman

install:

.include <bsd.prog.mk>
