# $OpenBSD: Makefile,v 1.11 2018/04/10 00:52:21 schwarze Exp $

REGRESS_TARGETS = argc divzero escname eval incr int predef rr scale tab undef
LINT_TARGETS	= divzero escname

.include <bsd.regress.mk>
