#	$OpenBSD: Makefile,v 1.12 2013/07/21 09:38:51 eric Exp $

.include <bsd.own.mk>

SUBDIR =	smtpd
SUBDIR+=	smtpctl
SUBDIR+=	makemap

SUBDIR+=	table-ldap
SUBDIR+=	table-passwd
SUBDIR+=	table-sqlite

.include <bsd.subdir.mk>
