#	$OpenBSD: Makefile,v 1.1 2009/01/28 13:40:48 mbalmer Exp $

PROG=		wake
SRCS=		wake.c
CFLAGS+=	-Wall -Wstrict-prototypes -Wmissing-prototypes
CFLAGS+=	-Wmissing-declarations -Wshadow -Wpointer-arith
CFLAGS+=	-Wcast-qual -Wsign-compare -Wbounded

MAN=		wake.8

.include <bsd.prog.mk>
