# $OpenBSD: Makefile.inc,v 1.6 2012/09/04 03:10:42 okan Exp $

SRCS+=	bcopy.c memcpy.c memmove.c \
	strchr.c strrchr.c \
	bcmp.c bzero.c ffs.c memchr.c memcmp.c memset.c \
	strcmp.c strncmp.c \
	strcat.c strcpy.c strcspn.c strlen.c strlcat.c strlcpy.c \
	strncat.c  strncpy.c strpbrk.c strsep.c \
	strspn.c swab.c strstr.c
