#	$OpenBSD: Makefile,v 1.1 2007/01/15 22:37:47 martin Exp $

# TODO: autoconf intro mainbus scif shb rsclock shpcic
MAN=	obio.4 power.4 mem.4
MANSUBDIR=landisk

#MLINKS+= mem.4 kmem.4
.include <bsd.prog.mk>
