#	$OpenBSD: Makefile,v 1.6 2017/01/23 11:07:18 otto Exp $

SUBDIR+= malloc_general malloc0test malloc_errno malloc_ulimit1 malloc_ulimit2
SUBDIR+= malloc_threaderr

install:

.include <bsd.subdir.mk>
