# $OpenBSD: Makefile,v 1.2 2017/07/09 15:28:35 espie Exp $

LIB=	LLVMIRReader
NOPROFILE=

CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/IRReader

SRCS+=	IRReader.cpp

.PATH:	${.CURDIR}/../../../llvm/lib/IRReader
