#	$OpenBSD: Makefile,v 1.10 2003/03/11 09:29:25 deraadt Exp $

SUBDIR=	adventure arithmetic atc backgammon banner battlestar bcd boggle \
	caesar canfield cribbage factor fish fortune gomoku grdc hack \
	hangman mille monop morse number phantasia pig pom ppt \
	primes quiz rain random robots sail snake tetris trek wargames \
	worm worms wump

.include <bsd.subdir.mk>
