#	$OpenBSD: Makefile,v 1.4 2001/01/29 02:05:33 niklas Exp $
#	$NetBSD: Makefile,v 1.5 1995/04/20 22:37:12 cgd Exp $

# missing: libexec sbin usr.bin usr.sbin share games gnu

SUBDIR+= bin include lib sys share usr.bin

regress: _SUBDIRUSE

install:

.include <bsd.subdir.mk>
