#	$OpenBSD: Makefile,v 1.3 1996/12/14 21:16:51 downsj Exp $

PROG=	praliases
MAN=	praliases.1
ENVDEF+=-DNOT_SENDMAIL

WANT_LIBSMDB=1
WANT_LIBSMUTIL=1

.include "../../Makefile.inc"
.include <bsd.prog.mk>
