#	$OpenBSD: Makefile,v 1.2 2001/04/09 06:55:40 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISKC
XNAME=floppyC
NOBSDRD=1

.include "${.CURDIR}/../common/Makefile.inc"

CRUNCHCONFS+=	${.CURDIR}/crunch_local.conf
LISTS+=		${.CURDIR}/list.local
