# $OpenBSD: Makefile,v 1.2 2014/07/02 08:03:57 schwarze Exp $

REGRESS_TARGETS	= before first emptyNAME badNAME order
LINT_TARGETS	= before first emptyNAME badNAME order

SKIP_GROFF	= first
SKIP_ASCII	= first

.include <bsd.regress.mk>
