# $OpenBSD: Makefile,v 1.1 2014/07/01 22:36:35 schwarze Exp $

REGRESS_TARGETS	= before first emptyNAME badNAME order
LINT_TARGETS	= before first emptyNAME badNAME order

SKIP_GROFF	= before first
SKIP_ASCII	= before first

.include <bsd.regress.mk>
