# $OpenBSD: Makefile,v 1.3 2014/07/07 15:03:24 schwarze Exp $

REGRESS_TARGETS	= before subbefore first emptyNAME badNAME order
LINT_TARGETS	= before subbefore first emptyNAME badNAME order

SKIP_GROFF	= subbefore first
SKIP_ASCII	= first

.include <bsd.regress.mk>
