#	$OpenBSD$

LIB=	common
SRCS=	allow.c board.c check.c fancy.c init.c odds.c one.c save.c subs.c \
	table.c

NOPROFILE=	noprofile
NOPIC=		nopic

# only needed during build
libinstall::

.include <bsd.lib.mk>
