#	$OpenBSD: Makefile,v 1.3 2002/03/14 19:39:16 jason Exp $

MAN=	intro.4tbl lasi.4 asp.4 gsc.4
# mongoose.4 hil.4 aone.4 harmony.4 wax.4 dino.4 tir.4 xbar.4 mcx.4
MANSUBDIR=hppa

.include <bsd.prog.mk>
