# $OpenBSD: Makefile,v 1.13 2017/06/14 18:23:26 schwarze Exp $

REGRESS_TARGETS	 = one two multi B c c_man e f h l O o p w z
REGRESS_TARGETS	+= ignore invalid unsupp
LINT_TARGETS	 = B h l O w ignore invalid unsupp

.include <bsd.regress.mk>
