# $OpenBSD: Makefile,v 1.4 2014/07/04 16:11:41 schwarze Exp $

REGRESS_TARGETS	= broken broken_eline noarg
LINT_TARGETS	= broken broken_eline noarg

SKIP_GROFF	= broken broken_eline noarg

.include <bsd.regress.mk>
