#	$OpenBSD: Makefile,v 1.1.1.1 1998/06/23 18:46:43 mickey Exp $

PROG=	mkboot
CC=	${HOSTCC}
CFLAGS+=-g
LDSTATIC=	-static
MAN=	mkboot.8
MANSUBDIR=/hppa
S=	${.CURDIR}/../../../..
SADIR=	${.CURDIR)/..

.include <bsd.prog.mk>
