#	$OpenBSD: Makefile,v 1.2 2000/05/18 13:49:51 espie Exp $
#	From: Makefile,v 1.1 1999/05/05 07:37:06 wpaul Exp $

PROG=	wicontrol
SRCS=	wicontrol.c

CFLAGS+= -Wall

MAN=	wicontrol.8

.include <bsd.prog.mk>
