#	$OpenBSD: Makefile,v 1.11 2016/10/19 16:43:02 bluhm Exp $

SUBDIR +=	etherip
SUBDIR +=	pf_divert pf_forward pf_fragment pf_print pf_state pf_table
SUBDIR +=	rdomains rtable vxlan

.include <bsd.subdir.mk>
