#	$OpenBSD: Makefile,v 1.18 2022/04/29 17:27:37 bluhm Exp $

SUBDIR +=	etherip gif loop
SUBDIR +=	pf_divert pf_forward pf_fragment pf_opts pf_policy pf_print
SUBDIR +=	pf_state pf_table
SUBDIR +=	pair pflog pflow rdomains rtable vxlan wg

.include <bsd.subdir.mk>
