#	$OpenBSD: Makefile,v 1.19 2023/01/09 10:21:40 sashan Exp $

SUBDIR +=	etherip gif loop mpath
SUBDIR +=	pf_divert pf_forward pf_fragment pf_opts pf_policy pf_print
SUBDIR +=	pf_state pf_table pf_trans
SUBDIR +=	pair pflog pflow rdomains rtable vxlan wg

.include <bsd.subdir.mk>
