#!/bin/sh
#
# $OpenBSD$

daemon="/usr/sbin/amd"

. /etc/rc.d/rc.subr

rc_reload=NO
rc_restart=NO
rc_stop=NO

rc_pre() {
	[ -e ${amd_master} ]
	daemon_flags=$(cat ${amd_master})
	return 0
}

rc_cmd $1
