#!/bin/ksh
#
# $OpenBSD: httpd,v 1.8 2022/05/21 12:42:21 ajacoutot Exp $

daemon="/usr/sbin/httpd"

. /etc/rc.d/rc.subr

rc_configtest() {
	# use rc_exec here since daemon_flags may contain arguments with spaces
	rc_exec "${daemon} -n ${daemon_flags}"
}

rc_cmd $1
