#!/bin/ksh
#
# $OpenBSD: iked,v 1.7 2019/01/21 01:41:16 claudio Exp $

daemon="/sbin/iked"

. /etc/rc.d/rc.subr

pexp="iked: parent.*"

# Child will not return a config parsing error to the parent.
rc_pre() {
	[[ ${sasyncd_flags} != NO ]] &&
		daemon_flags="-S ${daemon_flags}"

	# use rc_exec here since daemon_flags may contain arguments with spaces
	rc_exec "${daemon} -n ${daemon_flags}"
}

rc_cmd $1
