#!/bin/ksh
#
# $OpenBSD: iked,v 1.8 2022/05/21 12:42:21 ajacoutot Exp $

daemon="/sbin/iked"

. /etc/rc.d/rc.subr

pexp="iked: parent.*"

rc_configtest() {
	# use rc_exec here since daemon_flags may contain arguments with spaces
	rc_exec "${daemon} -n ${daemon_flags}"
}
rc_pre() {
	[[ ${sasyncd_flags} != NO ]] &&
		daemon_flags="-S ${daemon_flags}"
}

rc_cmd $1
