#!/bin/sh
#
# $OpenBSD$

daemon="/sbin/isakmpd"

. /etc/rc.d/rc.subr

pexp="isakmpd: monitor \[priv\]"

rc_pre() {
	[ X"${sasyncd_flags}" != X"NO" ] && \
		daemon_flags="-S ${daemon_flags}"
	return 0
}

rc_cmd $1
