#!/bin/sh
#
# $OpenBSD$

daemon="/usr/sbin/iscsid"
control="/usr/sbin/iscsictl"

. /etc/rc.d/rc.subr

rc_reload=NO
rc_stop=NO

rc_start() {
	${rcexec} "${daemon} ${daemon_flags} && ${control} reload"
}

rc_cmd $1
