#!/bin/sh
#
# $OpenBSD: mountd,v 1.2 2011/08/02 11:59:25 robert Exp $

daemon="/sbin/mountd"

. /etc/rc.d/rc.subr

rc_pre() {
	[ -s /etc/exports ] && grep -qv '^#' /etc/exports && \
		rm -f /var/db/mountdtab && \
		echo -n > /var/db/mountdtab
}

rc_cmd $1
