#!/bin/sh
#
# $OpenBSD$

daemon="/sbin/nfsd"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_pre() {
	[ -s /etc/exports -a `sed -e '/^#/d' < /etc/exports | wc -l` -ne 0 ] &&
		rm -f /var/db/mountdtab && \
		echo -n > /var/db/mountdtab
}

rc_post() {
	pkill -f "^nfsd: server$"
}

rc_cmd $1
