#!/bin/sh
#
# $OpenBSD: nfsd,v 1.2 2011/08/02 11:50:39 robert Exp $

daemon="/sbin/nfsd"

. /etc/rc.d/rc.subr

pexp="(${daemon}*|nfsd: (master|server)$)"

rc_reload=NO

rc_pre() {
	[ -s /etc/exports -a `sed -e '/^#/d' < /etc/exports | wc -l` -ne 0 ]
}

rc_cmd $1
