#!/bin/sh
#
# $OpenBSD: nfsd,v 1.5 2012/08/14 07:43:57 ajacoutot Exp $

daemon="/sbin/nfsd"
daemon_flags="-tun 4"

. /etc/rc.d/rc.subr

pexp="(${daemon}( |$)|nfsd: (master|server)$)"

rc_reload=NO

rc_pre() {
	[ -s /etc/exports ] && grep -qv '^#' /etc/exports
}

rc_cmd $1
