#!/bin/ksh
#
# $OpenBSD: nsd,v 1.10 2018/01/11 19:52:12 rpe Exp $

daemon="/usr/sbin/nsd-control"
daemon_flags="-c /var/nsd/etc/nsd.conf"

. /etc/rc.d/rc.subr

rc_usercheck=NO

rc_start() {
	${rcexec} "${daemon} ${daemon_flags} start"
}

rc_check() {
	${daemon} ${daemon_flags} status || return 1
}

rc_reload() {
	${daemon} ${daemon_flags} reconfig && ${daemon} ${daemon_flags} reload
}

rc_stop() {
	${daemon} ${daemon_flags} stop
}

rc_cmd $1
