#!/bin/ksh
#
# $OpenBSD: rad,v 1.1 2018/07/12 08:20:36 florian Exp $

daemon="/usr/sbin/rad"

. /etc/rc.d/rc.subr

rc_configtest() {
	# use rc_exec here since daemon_flags may contain arguments with spaces
	rc_exec "${daemon} -n ${daemon_flags}"
}

rc_cmd $1
