#!/bin/ksh
#
# $OpenBSD: relayd,v 1.4 2018/01/11 19:52:12 rpe Exp $

daemon="/usr/sbin/relayd"

. /etc/rc.d/rc.subr

# Child will not return a config parsing error to the parent.
rc_pre() {
	${daemon} -n ${daemon_flags}
}

rc_cmd $1
