#!/bin/sh
#
# $OpenBSD: sndiod,v 1.2 2011/12/28 14:58:16 ajacoutot Exp $

daemon="/usr/bin/sndiod"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_check() {
	pgrep -T "${daemon_rtable}" -U _sndio -q -xf "${pexp}"
}

rc_reload() {
	pkill -T "${daemon_rtable}" -U _sndio -HUP -xf "${pexp}"
}

rc_stop() {
	pkill -T "${daemon_rtable}" -U _sndio -xf "${pexp}"
}

rc_cmd $1
