#!/bin/sh
#
# $OpenBSD: vmd,v 1.2 2015/12/16 14:21:28 jturner Exp $

daemon="/usr/sbin/vmd"

. /etc/rc.d/rc.subr

pexp="vmd: parent.*"

# child will not return a config parsing error to the parent
rc_pre() {
	${daemon} -n ${daemon_flags}
}

rc_cmd $1
