#!/bin/ksh
#
# $OpenBSD: vmd,v 1.8 2018/07/11 13:19:47 reyk Exp $

daemon="/usr/sbin/vmd"

. /etc/rc.d/rc.subr

# Child will not return a config parsing error to the parent.
rc_pre() {
	${daemon} -n ${daemon_flags}
}

rc_stop() {
	_rc_do vmctl stop -a -w
	pkill -T "${daemon_rtable}" -xf "${pexp}"
}

rc_cmd $1
