#!/bin/ksh
#
# $OpenBSD: ypbind,v 1.8 2018/01/11 19:52:12 rpe Exp $

daemon="/usr/sbin/ypbind"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_pre() {
	[[ -n $(domainname) ]]
}

rc_post() {
	rm -f /var/run/ypbind.lock
}

rc_cmd $1
