#	$OpenBSD: Makefile.inc,v 1.1 1995/07/18 04:12:57 briggs Exp $
#	$NetBSD: Makefile.inc,v 1.1 1995/07/18 04:12:57 briggs Exp $

# Revision is 2.1
REV=	21

BSDSRCDIR?=     /usr/src
SRCSYSDIR?=     ${BSDSRCDIR}/sys
