#	$OpenBSD$

SRCS+=	bcmp.c bzero.c bcopy.c memchr.c memcmp.c memset.c index.c rindex.c \
	strcat.c strcmp.c strcpy.c strlcpy.c strcspn.c strlen.c \
	strncat.c strncmp.c strncpy.c strpbrk.c strsep.c \
	strspn.c strstr.c swab.c ffs.c

