# $OpenBSD: Makefile,v 1.10 2020/02/27 01:25:58 schwarze Exp $

REGRESS_TARGETS = bullet empty literal longhead manyargs spacing tag vert width
TAG_TARGETS	= empty tag
UTF8_TARGETS	= bullet
LINT_TARGETS	= empty
HTML_TARGETS	= bullet empty literal tag

.include <bsd.regress.mk>
