# $OpenBSD: Makefile,v 1.9 2019/01/06 04:41:15 schwarze Exp $

REGRESS_TARGETS = bullet empty literal longhead manyargs spacing vert width
UTF8_TARGETS	= bullet
LINT_TARGETS	= empty
HTML_TARGETS	= bullet literal

.include <bsd.regress.mk>
