#!/bin/sh -x
#	$OpenBSD: checkflist,v 1.3 2000/03/01 22:10:08 todd Exp $

if [ "X${DESTDIR}" = "X" ]; then
	echo DESTDIR must be set
	exit 1
fi

TMP=`mktemp /tmp/_ckr.XXXXXX` || exit 1
trap 'rm -f $TMP' 0 1 15

sh makeflist > $TMP
( cd $DESTDIR ; find . \( -type d -o -type f -o -type l \) ) | sort | \
    diff $TMP -
