#	$OpenBSD: Makefile,v 1.3 1996/09/16 10:16:55 downsj Exp $

LDSTATIC=${STATIC}
PROG=	ktrace
SRCS=	ktrace.c subr.c
MAN=	ktrace.1 ltrace.1

LINKS=	${BINDIR}/ktrace ${BINDIR}/ltrace

.include <bsd.prog.mk>
