# $OpenBSD: Makefile,v 1.7 2020/08/03 14:45:25 patrick Exp $

LIB=	LLVMAsmPrinter
NOPROFILE=

SRCS+=	AccelTable.cpp \
	AddressPool.cpp \
	ARMException.cpp \
	AsmPrinter.cpp \
	AsmPrinterDwarf.cpp \
	AsmPrinterInlineAsm.cpp \
	DbgEntityHistoryCalculator.cpp \
	DebugHandlerBase.cpp \
	DebugLocStream.cpp \
	DIE.cpp \
	DIEHash.cpp \
	DwarfCFIException.cpp \
	DwarfCompileUnit.cpp \
	DwarfDebug.cpp \
	DwarfExpression.cpp \
	DwarfFile.cpp \
	DwarfStringPool.cpp \
	DwarfUnit.cpp \
	EHStreamer.cpp \
	ErlangGCPrinter.cpp \
	OcamlGCPrinter.cpp \
	WinCFGuard.cpp \
	WinException.cpp \
	CodeViewDebug.cpp \
	WasmException.cpp


.PATH:	${.CURDIR}/../../../llvm/llvm/lib/CodeGen/AsmPrinter
