#	$OpenBSD: Makefile,v 1.1 2007/01/28 19:10:06 kettenis Exp $

PROG=	simple2
SRCS=	simple2.cc
# This flag has been known to trigger bugs in clang, please keep it
CXXFLAGS=-O0

.include <bsd.regress.mk>
