# $OpenBSD: Makefile,v 1.4 2010/04/13 22:49:47 schwarze Exp $

REGRESS_TARGETS=tag inset hang diag column multitag extend nested multitype
GROFF_TARGETS=tag inset hang diag column multitag extend nested multitype

REGRESS_TARGETS+=EMULTILIST
REGRESS_SLOW_TARGETS=EMULTILIST

.include <bsd.regress.mk>
