# $OpenBSD$

REGRESS_TARGETS = case badsec badarch nodate baddate noos order dupe lateos
LINT_TARGETS = case badsec badarch nodate baddate noos order dupe lateos
SKIP_GROFF = badsec badarch nodate baddate noos
SKIP_ASCII = badsec badarch nodate baddate noos

.include <bsd.regress.mk>
