#	$OpenBSD: Makefile,v 1.3 1995/09/02 06:15:10 jtc Exp $
#	$NetBSD: Makefile,v 1.3 1995/09/02 06:15:10 jtc Exp $

PROG=	error
SRCS=	main.c input.c pi.c subr.c filter.c touch.c

.include <bsd.prog.mk>
