#	$OpenBSD: Makefile,v 1.4 1998/08/22 08:57:27 smurph Exp $
.if ${MACHINE} == "mvme88k"

SUBDIR=  bugcrt libbug libsa libz wrtvid bootsd bootxx bootst netboot
#sboot XXX future
.endif

SUBDIR+=installboot

.include <bsd.subdir.mk>
