# $OpenBSD$

LIB=	LLVMMCDisassembler
NOPIC=
NOPROFILE=

.include <bsd.own.mk>
SRCS=	Disassembler.cpp \
	MCRelocationInfo.cpp \
	MCExternalSymbolizer.cpp \
	MCDisassembler.cpp

.PATH:	${.CURDIR}/../../../llvm/lib/MC/MCDisassembler

depend:
	# Nothing here so far ...

install:
	# Nothing here so far ...

.include <bsd.lib.mk>
