#	$OpenBSD: Makefile,v 1.23 2005/11/24 20:49:20 deraadt Exp $

#
# librthread still uses this
#

SRCDIR=		${.CURDIR}
LIBCSRCDIR=	${.CURDIR}/../libc

.include "${SRCDIR}/include/Makefile.inc"
.include "${SRCDIR}/sys/Makefile.inc"
.include "${SRCDIR}/thread/Makefile.inc"
.include "${SRCDIR}/uthread/Makefile.inc"
.include "${SRCDIR}/man/Makefile.inc"

.include <bsd.lib.mk>
