# $OpenBSD: Makefile,v 1.6 2014/07/04 16:11:42 schwarze Exp $

REGRESS_TARGETS	 = badarg break broken inputlines lines synopsis
LINT_TARGETS	 = badarg broken

SKIP_TMAN ?= badarg

.include <bsd.regress.mk>
