#	$OpenBSD: Makefile,v 1.30 2005/09/28 16:20:01 drahn Exp $

SRCS=	prebind_strip.c

PROG=	prebind_strip
MAN= prebind_strip.8

BINDIR=/usr/sbin

CFLAGS += -Wall -ggdb
CFLAGS += -I${.CURDIR}/..

.include <bsd.prog.mk>
