#	$OpenBSD: Makefile,v 1.27 2018/11/07 01:20:20 bluhm Exp $

SUBDIR= \
	asn1 \
	bytestring \
	ciphers \
	client \
	interop \
	pqueue \
	server \
	ssl \
	tlsext \
	key_schedule \
	unit

install:

.include <bsd.subdir.mk>
