#	$OpenBSD: Makefile,v 1.30 2018/11/09 19:31:50 tb Exp $

SUBDIR += asn1
SUBDIR += bytestring
SUBDIR += ciphers
SUBDIR += client
SUBDIR += pqueue
SUBDIR += server
SUBDIR += ssl
SUBDIR += tlsext
SUBDIR += key_schedule
SUBDIR += unit
# Things that take a long time shoud go below here. 
SUBDIR += interop

install:

.include <bsd.subdir.mk>
