#	$OpenBSD: Makefile,v 1.28 2018/11/07 21:42:10 beck Exp $

SUBDIR += asn1
SUBDIR += bytestring
SUBDIR += ciphers
SUBDIR += client
SUBDIR += handshake
SUBDIR += interop
SUBDIR += pqueue
SUBDIR += server
SUBDIR += ssl
SUBDIR += tlsext
SUBDIR += key_schedule
SUBDIR += unit

install:

.include <bsd.subdir.mk>
