# $OpenBSD: Makefile,v 1.8 2004/02/25 14:22:12 henning Exp $

.include <bsd.own.mk>

SRCS=	dhcrelay.c dispatch.c errwarn.c bpf.c packet.c alloc.c
PROG=	dhcrelay
MAN=	dhcrelay.8

CFLAGS+=-Wall

.include <bsd.prog.mk>
