# $OpenBSD: Makefile,v 1.4 2014/06/20 18:32:51 schwarze Exp $

REGRESS_TARGETS  = noarg onearg twoargs sixargs case
REGRESS_TARGETS += emptydate onlyyear isodate mdocdate baddate
REGRESS_TARGETS += nobody

LINT_TARGETS = noTH case twoargs emptydate baddate nobody

.include <bsd.regress.mk>
