#	$OpenBSD: Makefile,v 1.1.1.1 1995/10/18 08:45:23 deraadt Exp $

PROG=	hexdump
SRCS=	conv.c display.c hexdump.c hexsyntax.c odsyntax.c parse.c
MAN=	hexdump.1 od.1
LINKS=	${BINDIR}/hexdump ${BINDIR}/od

.include <bsd.prog.mk>
