#	$OpenBSD: Makefile,v 1.5 1997/09/21 11:38:02 deraadt Exp $

COPTS+=-Os
PROG=	restore
SRCS=	main.c interactive.c restore.c dirs.c symtab.c tape.c utilities.c
MAN=

.PATH:	${.CURDIR}/../../../sbin/restore

.include <bsd.prog.mk>
