# $FreeBSD: src/gnu/usr.bin/cc/cpp/Makefile,v 1.27.8.1 2009/04/15 03:14:26 kensmith Exp $
# $OpenBSD$

.include <bsd.own.mk>

.include "${.CURDIR}/../Makefile.inc"
.include "${.CURDIR}/../Makefile.fe"

PROG=	cpp
SRCS+=	cppspec.c

.include <bsd.prog.mk>
