# $OpenBSD: Makefile,v 1.7 2002/06/11 15:26:49 hin Exp $

# XXX asn1_compile is compiled in ../Makefile

# kf
SUBDIR=	afslog \
	kauth \
	kdestroy \
	kinit \
	klist \
	pagsh \
	string2key \
	verify_krb5_conf

.include <bsd.subdir.mk>
