# $OpenBSD: Makefile,v 1.6 2001/06/27 16:17:09 hin Exp $

# XXX asn1_compile is compiled in ../Makefile

SUBDIR=	afslog \
	kauth \
	kdestroy \
	kf \
	kinit \
	klist \
	pagsh \
	string2key \
	verify_krb5_conf

.include <bsd.subdir.mk>
