#	$OpenBSD: Makefile,v 1.3 1995/03/26 20:14:03 glass Exp $
#	$NetBSD: Makefile,v 1.3 1995/03/26 20:14:03 glass Exp $

PROG=	ctags
CFLAGS+=-I${.CURDIR}
SRCS=	C.c ctags.c fortran.c lisp.c print.c tree.c yacc.c

.include <bsd.prog.mk>
