name: perl
version: 5.010001
abstract: Practical Extraction and Report Language
author: perl5-porters@perl.org
license: perl
resources:
  homepage: http://www.perl.org/
  bugtracker: http://rt.perl.org/perlbug/
  license: http://dev.perl.org/licenses/
distribution_type: core
generated_by: Porting/makemeta
no_index:
  directory:
    - ext/Attribute-Handlers
    - ext/Compress-Raw-Bzip2
    - ext/Compress-Raw-Zlib
    - ext/Cwd
    - ext/Data-Dumper
    - ext/DB_File
    - ext/Devel-PPPort
    - ext/Digest-MD5
    - ext/Digest-SHA
    - ext/Encode
    - ext/Filter-Util-Call
    - ext/IO-Compress
    - ext/IO/
    - ext/IPC-SysV
    - ext/List-Util
    - ext/Math-BigInt-FastCalc
    - ext/MIME-Base64
    - ext/Module-Pluggable
    - ext/Safe
    - ext/Storable
    - ext/Sys-Syslog
    - ext/Test-Harness
    - ext/Text-Soundex
    - ext/threads
    - ext/threads-shared
    - ext/Time-HiRes
    - ext/Time-Piece
    - ext/Unicode-Normalize
    - ext/Win32
    - ext/Win32API-File
    - lib/Archive/Extract
    - lib/Archive/Tar
    - lib/autodie
    - lib/AutoLoader
    - lib/base
    - lib/bignum
    - lib/CGI
    - lib/Class/ISA
    - lib/CPAN
    - lib/CPANPLUS/Backend
    - lib/CPANPLUS/bin
    - lib/CPANPLUS/Configure
    - lib/CPANPLUS/Dist/Build
    - lib/CPANPLUS/Internals
    - lib/CPANPLUS/Module
    - lib/CPANPLUS/Shell
    - lib/CPANPLUS/t
    - lib/Digest
    - lib/encoding/warnings
    - lib/ExtUtils/CBuilder
    - lib/ExtUtils/Constant
    - lib/ExtUtils/ParseXS
    - lib/ExtUtils/t/testdata/
    - lib/File/Fetch
    - lib/File/Spec
    - lib/File/Temp
    - lib/Filter/Simple
    - lib/Getopt/Long
    - lib/IO/Zlib
    - lib/IPC/Cmd
    - lib/Locale/Maketext/Simple
    - lib/Locale/Maketext/t
    - lib/Log/Message/Simple
    - lib/Log/Message/t
    - lib/Math/BigInt
    - lib/Math/BigRat
    - lib/Memoize
    - lib/Module/Build
    - lib/Module/CoreList
    - lib/Module/Load/Conditional
    - lib/Module/Load/t
    - lib/Module/Loaded
    - lib/Net/demos/
    - lib/Net/FTP
    - lib/Net/Ping
    - lib/Net/t
    - lib/NEXT
    - lib/Object/Accessor
    - lib/Package/Constants
    - lib/Params/Check
    - lib/parent
    - lib/Parse/CPAN/Meta
    - lib/Pod/Escapes
    - lib/Pod/Perldoc
    - lib/Pod/Simple
    - lib/SelfLoader
    - lib/Switch
    - lib/Term/ANSIColor
    - lib/Term/UI
    - lib/Test/Builder
    - lib/Test/Simple
    - lib/Test/t
    - lib/Text/Balanced
    - lib/Text/TabsWrap
    - lib/Thread/Queue
    - lib/Thread/Semaphore
    - lib/Tie/File
    - lib/Tie/RefHash
    - lib/Unicode/Collate
    - lib/version
    - t/lib/compress
    - t/lib/Filter/Simple/
    - t/lib/MakeMaker
    - t/lib/Math/BigFloat/
    - t/lib/Math/BigInt/
    - t/lib/Math/BigRat/
    - t/lib/Test/
    - t/pod/testpods/

  file:
    - ext/B/B/Debug.pm
    - ext/B/B/Lint.pm
    - ext/B/B/Lint/Debug.pm
    - ext/B/t/debug.t
    - ext/B/t/lint.t
    - ext/B/t/pluglib/B/Lint/Plugin/Test.pm
    - ext/DynaLoader/t/XSLoader.t
    - ext/DynaLoader/XSLoader_pm.PL
    - ext/IO/ChangeLog
    - ext/IO/hints/sco.pl
    - ext/IO/IO.pm
    - ext/IO/IO.xs
    - ext/IO/lib/IO/Dir.pm
    - ext/IO/lib/IO/File.pm
    - ext/IO/lib/IO/Handle.pm
    - ext/IO/lib/IO/Pipe.pm
    - ext/IO/lib/IO/Poll.pm
    - ext/IO/lib/IO/Seekable.pm
    - ext/IO/lib/IO/Select.pm
    - ext/IO/lib/IO/Socket.pm
    - ext/IO/lib/IO/Socket/INET.pm
    - ext/IO/lib/IO/Socket/UNIX.pm
    - ext/IO/Makefile.PL
    - ext/IO/poll.c
    - ext/IO/poll.h
    - ext/IO/README
    - ext/IO/t/IO.t
    - ext/IO/t/io_const.t
    - ext/IO/t/io_dir.t
    - ext/IO/t/io_dup.t
    - ext/IO/t/io_file.t
    - ext/IO/t/io_linenum.t
    - ext/IO/t/io_multihomed.t
    - ext/IO/t/io_pipe.t
    - ext/IO/t/io_poll.t
    - ext/IO/t/io_sel.t
    - ext/IO/t/io_sock.t
    - ext/IO/t/io_taint.t
    - ext/IO/t/io_tell.t
    - ext/IO/t/io_udp.t
    - ext/IO/t/io_unix.t
    - ext/IO/t/io_utf8.t
    - ext/IO/t/io_xs.t
    - lib/Archive/Extract.pm
    - lib/Archive/Tar.pm
    - lib/autodie.pm
    - lib/AutoLoader.pm
    - lib/AutoSplit.pm
    - lib/base.pm
    - lib/bigint.pm
    - lib/bignum.pm
    - lib/bigrat.pm
    - lib/CGI.pm
    - lib/Class/ISA.pm
    - lib/constant.pm
    - lib/constant.t
    - lib/CPAN.pm
    - lib/CPANPLUS.pm
    - lib/CPANPLUS/Backend.pm
    - lib/CPANPLUS/Config.pm
    - lib/CPANPLUS/Configure.pm
    - lib/CPANPLUS/Dist.pm
    - lib/CPANPLUS/Dist/Autobundle.pm
    - lib/CPANPLUS/Dist/Base.pm
    - lib/CPANPLUS/Dist/Build.pm
    - lib/CPANPLUS/Dist/MM.pm
    - lib/CPANPLUS/Dist/Sample.pm
    - lib/CPANPLUS/Error.pm
    - lib/CPANPLUS/FAQ.pod
    - lib/CPANPLUS/Hacking.pod
    - lib/CPANPLUS/Internals.pm
    - lib/CPANPLUS/Module.pm
    - lib/CPANPLUS/Selfupdate.pm
    - lib/CPANPLUS/Shell.pm
    - lib/Cwd.pm
    - lib/Digest.pm
    - lib/encoding/warnings.pm
    - lib/Exporter.pm
    - lib/Exporter.t
    - lib/Exporter/Heavy.pm
    - lib/ExtUtils/CBuilder.pm
    - lib/ExtUtils/Changes
    - lib/ExtUtils/Changes_EU-Install
    - lib/ExtUtils/Command.pm
    - lib/ExtUtils/Command/MM.pm
    - lib/ExtUtils/Constant.pm
    - lib/ExtUtils/Install.pm
    - lib/ExtUtils/Installed.pm
    - lib/ExtUtils/instmodsh
    - lib/ExtUtils/Liblist.pm
    - lib/ExtUtils/Liblist/Kid.pm
    - lib/ExtUtils/MakeMaker.pm
    - lib/ExtUtils/MakeMaker/Config.pm
    - lib/ExtUtils/MakeMaker/FAQ.pod
    - lib/ExtUtils/MakeMaker/Tutorial.pod
    - lib/ExtUtils/Manifest.pm
    - lib/ExtUtils/MANIFEST.SKIP
    - lib/ExtUtils/Mkbootstrap.pm
    - lib/ExtUtils/Mksymlists.pm
    - lib/ExtUtils/MM.pm
    - lib/ExtUtils/MM_AIX.pm
    - lib/ExtUtils/MM_Any.pm
    - lib/ExtUtils/MM_BeOS.pm
    - lib/ExtUtils/MM_Cygwin.pm
    - lib/ExtUtils/MM_Darwin.pm
    - lib/ExtUtils/MM_DOS.pm
    - lib/ExtUtils/MM_MacOS.pm
    - lib/ExtUtils/MM_NW5.pm
    - lib/ExtUtils/MM_OS2.pm
    - lib/ExtUtils/MM_QNX.pm
    - lib/ExtUtils/MM_Unix.pm
    - lib/ExtUtils/MM_UWIN.pm
    - lib/ExtUtils/MM_VMS.pm
    - lib/ExtUtils/MM_VOS.pm
    - lib/ExtUtils/MM_Win32.pm
    - lib/ExtUtils/MM_Win95.pm
    - lib/ExtUtils/MY.pm
    - lib/ExtUtils/NOTES
    - lib/ExtUtils/Packlist.pm
    - lib/ExtUtils/ParseXS.pm
    - lib/ExtUtils/PATCHING
    - lib/ExtUtils/README
    - lib/ExtUtils/t/00compile.t
    - lib/ExtUtils/t/arch_check.t
    - lib/ExtUtils/t/backwards.t
    - lib/ExtUtils/t/basic.t
    - lib/ExtUtils/t/build_man.t
    - lib/ExtUtils/t/can_write_dir.t
    - lib/ExtUtils/t/cd.t
    - lib/ExtUtils/t/config.t
    - lib/ExtUtils/t/Constant.t
    - lib/ExtUtils/t/cp.t
    - lib/ExtUtils/t/dir_target.t
    - lib/ExtUtils/t/eu_command.t
    - lib/ExtUtils/t/FIRST_MAKEFILE.t
    - lib/ExtUtils/t/fix_libs.t
    - lib/ExtUtils/t/fixin.t
    - lib/ExtUtils/t/hints.t
    - lib/ExtUtils/t/INST.t
    - lib/ExtUtils/t/INST_PREFIX.t
    - lib/ExtUtils/t/Install.t
    - lib/ExtUtils/t/INSTALL_BASE.t
    - lib/ExtUtils/t/Installapi2.t
    - lib/ExtUtils/t/Installed.t
    - lib/ExtUtils/t/installed_file.t
    - lib/ExtUtils/t/InstallWithMM.t
    - lib/ExtUtils/t/is_of_type.t
    - lib/ExtUtils/t/Liblist.t
    - lib/ExtUtils/t/make.t
    - lib/ExtUtils/t/MakeMaker_Parameters.t
    - lib/ExtUtils/t/maketext_filter.t
    - lib/ExtUtils/t/Manifest.t
    - lib/ExtUtils/t/metafile_data.t
    - lib/ExtUtils/t/metafile_file.t
    - lib/ExtUtils/t/min_perl_version.t
    - lib/ExtUtils/t/miniperl.t
    - lib/ExtUtils/t/Mkbootstrap.t
    - lib/ExtUtils/t/MM_Any.t
    - lib/ExtUtils/t/MM_BeOS.t
    - lib/ExtUtils/t/MM_Cygwin.t
    - lib/ExtUtils/t/MM_NW5.t
    - lib/ExtUtils/t/MM_OS2.t
    - lib/ExtUtils/t/MM_Unix.t
    - lib/ExtUtils/t/MM_VMS.t
    - lib/ExtUtils/t/MM_Win32.t
    - lib/ExtUtils/t/oneliner.t
    - lib/ExtUtils/t/Packlist.t
    - lib/ExtUtils/t/parse_version.t
    - lib/ExtUtils/t/PL_FILES.t
    - lib/ExtUtils/t/pm.t
    - lib/ExtUtils/t/pm_to_blib.t
    - lib/ExtUtils/t/pod2man.t
    - lib/ExtUtils/t/postamble.t
    - lib/ExtUtils/t/prefixify.t
    - lib/ExtUtils/t/prereq.t
    - lib/ExtUtils/t/prereq_print.t
    - lib/ExtUtils/t/problems.t
    - lib/ExtUtils/t/prompt.t
    - lib/ExtUtils/t/recurs.t
    - lib/ExtUtils/t/revision.t
    - lib/ExtUtils/t/split_command.t
    - lib/ExtUtils/t/test_boilerplate.t
    - lib/ExtUtils/t/testdata/reallylongdirectoryname/arch1/Config.pm
    - lib/ExtUtils/t/testdata/reallylongdirectoryname/arch2/Config.pm
    - lib/ExtUtils/t/testlib.t
    - lib/ExtUtils/t/VERSION_FROM.t
    - lib/ExtUtils/t/WriteEmptyMakefile.t
    - lib/ExtUtils/t/writemakefile_args.t
    - lib/ExtUtils/t/xs.t
    - lib/ExtUtils/testlib.pm
    - lib/ExtUtils/TODO
    - lib/ExtUtils/xsubpp
    - lib/Fatal.pm
    - lib/fields.pm
    - lib/File/Fetch.pm
    - lib/File/Path.pm
    - lib/File/Path.t
    - lib/File/Spec.pm
    - lib/File/Temp.pm
    - lib/Filter/Simple.pm
    - lib/Getopt/Long.pm
    - lib/if.pm
    - lib/if.t
    - lib/IO/Zlib.pm
    - lib/IPC/Cmd.pm
    - lib/lib.t
    - lib/lib_pm.PL
    - lib/Locale/Codes/ChangeLog
    - lib/Locale/Codes/README
    - lib/Locale/Codes/t/all.t
    - lib/Locale/Codes/t/constants.t
    - lib/Locale/Codes/t/country.t
    - lib/Locale/Codes/t/currency.t
    - lib/Locale/Codes/t/languages.t
    - lib/Locale/Codes/t/rename.t
    - lib/Locale/Codes/t/script.t
    - lib/Locale/Codes/t/uk.t
    - lib/Locale/Constants.pm
    - lib/Locale/Constants.pod
    - lib/Locale/Country.pm
    - lib/Locale/Country.pod
    - lib/Locale/Currency.pm
    - lib/Locale/Currency.pod
    - lib/Locale/Language.pm
    - lib/Locale/Language.pod
    - lib/Locale/Maketext.pm
    - lib/Locale/Maketext.pod
    - lib/Locale/Maketext/ChangeLog
    - lib/Locale/Maketext/Guts.pm
    - lib/Locale/Maketext/GutsLoader.pm
    - lib/Locale/Maketext/README
    - lib/Locale/Maketext/Simple.pm
    - lib/Locale/Maketext/TPJ13.pod
    - lib/Locale/Script.pm
    - lib/Locale/Script.pod
    - lib/Log/Message.pm
    - lib/Log/Message/Config.pm
    - lib/Log/Message/Handlers.pm
    - lib/Log/Message/Item.pm
    - lib/Log/Message/Simple.pm
    - lib/Math/BigFloat.pm
    - lib/Math/BigFloat/Trace.pm
    - lib/Math/BigInt.pm
    - lib/Math/BigRat.pm
    - lib/Math/Complex.pm
    - lib/Math/Complex.t
    - lib/Math/Trig.pm
    - lib/Math/Trig.t
    - lib/Math/underbar.t
    - lib/Memoize.pm
    - lib/Module/Build.pm
    - lib/Module/CoreList.pm
    - lib/Module/Load.pm
    - lib/Module/Load/Conditional.pm
    - lib/Module/Loaded.pm
    - lib/Net/Changes
    - lib/Net/Cmd.pm
    - lib/Net/Config.eg
    - lib/Net/Config.pm
    - lib/Net/demos/ftp
    - lib/Net/demos/inetd
    - lib/Net/demos/nntp
    - lib/Net/demos/nntp.mirror
    - lib/Net/demos/pop3
    - lib/Net/demos/smtp.self
    - lib/Net/demos/time
    - lib/Net/Domain.pm
    - lib/Net/FTP.pm
    - lib/Net/Hostname.pm.eg
    - lib/Net/libnetFAQ.pod
    - lib/Net/Netrc.pm
    - lib/Net/NNTP.pm
    - lib/Net/Ping.pm
    - lib/Net/POP3.pm
    - lib/Net/README
    - lib/Net/SMTP.pm
    - lib/Net/Time.pm
    - lib/newgetopt.pl
    - lib/NEXT.pm
    - lib/Object/Accessor.pm
    - lib/Package/Constants.pm
    - lib/Params/Check.pm
    - lib/parent.pm
    - lib/Parse/CPAN/Meta.pm
    - lib/PerlIO/via/QuotedPrint.pm
    - lib/PerlIO/via/t/QuotedPrint.t
    - lib/Pod/Checker.pm
    - lib/Pod/Escapes.pm
    - lib/Pod/Find.pm
    - lib/Pod/InputObjects.pm
    - lib/Pod/LaTeX.pm
    - lib/Pod/Man.pm
    - lib/Pod/ParseLink.pm
    - lib/Pod/Parser.pm
    - lib/Pod/ParseUtils.pm
    - lib/Pod/Perldoc.pm
    - lib/Pod/PlainText.pm
    - lib/Pod/Select.pm
    - lib/Pod/Simple.pm
    - lib/Pod/Simple.pod
    - lib/Pod/t/basic.cap
    - lib/Pod/t/basic.clr
    - lib/Pod/t/basic.man
    - lib/Pod/t/basic.ovr
    - lib/Pod/t/basic.pod
    - lib/Pod/t/basic.t
    - lib/Pod/t/basic.txt
    - lib/Pod/t/color.t
    - lib/Pod/t/contains_pod.t
    - lib/Pod/t/filehandle.t
    - lib/Pod/t/man-options.t
    - lib/Pod/t/man-utf8.t
    - lib/Pod/t/man.t
    - lib/Pod/t/parselink.t
    - lib/Pod/t/pod-parser.t
    - lib/Pod/t/pod-spelling.t
    - lib/Pod/t/pod.t
    - lib/Pod/t/pod2latex.t
    - lib/Pod/t/termcap.t
    - lib/Pod/t/text-encoding.t
    - lib/Pod/t/text-options.t
    - lib/Pod/t/text-utf8.t
    - lib/Pod/t/text.t
    - lib/Pod/t/user.t
    - lib/Pod/Text.pm
    - lib/Pod/Text/Color.pm
    - lib/Pod/Text/Overstrike.pm
    - lib/Pod/Text/Termcap.pm
    - lib/Pod/Usage.pm
    - lib/SelfLoader.pm
    - lib/Shell.pm
    - lib/Shell.t
    - lib/Switch.pm
    - lib/Term/ANSIColor.pm
    - lib/Term/Cap.pm
    - lib/Term/Cap.t
    - lib/Term/UI.pm
    - lib/Test.pm
    - lib/Test/Builder.pm
    - lib/Test/More.pm
    - lib/Test/Simple.pm
    - lib/Test/Tutorial.pod
    - lib/Text/Balanced.pm
    - lib/Text/ParseWords.pm
    - lib/Text/ParseWords.t
    - lib/Text/ParseWords/taint.t
    - lib/Text/Tabs.pm
    - lib/Text/Wrap.pm
    - lib/Thread/Queue.pm
    - lib/Thread/Semaphore.pm
    - lib/Tie/File.pm
    - lib/Tie/RefHash.pm
    - lib/Time/Local.pm
    - lib/Time/Local.t
    - lib/Unicode/Collate.pm
    - lib/version.pm
    - lib/version.pod
    - lib/version.t
    - pod/perldoc.pod
    - pod/perlfilter.pod
    - pod/pod2latex.PL
    - pod/pod2man.PL
    - pod/pod2text.PL
    - pod/pod2usage.PL
    - pod/podchecker.PL
    - pod/podselect.PL
    - t/lib/contains_bad_pod.xr
    - t/lib/contains_pod.xr
    - t/lib/Dev/Null.pm
    - t/lib/filter-util.pl
    - t/lib/Filter/Simple/ExportTest.pm
    - t/lib/Filter/Simple/FilterOnlyTest.pm
    - t/lib/Filter/Simple/FilterTest.pm
    - t/lib/Filter/Simple/ImportTest.pm
    - t/lib/Math/BigFloat/Subclass.pm
    - t/lib/Math/BigInt/BareCalc.pm
    - t/lib/Math/BigInt/Scalar.pm
    - t/lib/Math/BigInt/Subclass.pm
    - t/lib/Math/BigRat/Test.pm
    - t/lib/Parse/CPAN/Meta/Test.pm
    - t/lib/Test/Builder/NoOutput.pm
    - t/lib/Test/Simple/Catch.pm
    - t/lib/Test/Simple/sample_tests/death.plx
    - t/lib/Test/Simple/sample_tests/death_in_eval.plx
    - t/lib/Test/Simple/sample_tests/death_with_handler.plx
    - t/lib/Test/Simple/sample_tests/exit.plx
    - t/lib/Test/Simple/sample_tests/extras.plx
    - t/lib/Test/Simple/sample_tests/five_fail.plx
    - t/lib/Test/Simple/sample_tests/last_minute_death.plx
    - t/lib/Test/Simple/sample_tests/one_fail.plx
    - t/lib/Test/Simple/sample_tests/pre_plan_death.plx
    - t/lib/Test/Simple/sample_tests/require.plx
    - t/lib/Test/Simple/sample_tests/success.plx
    - t/lib/Test/Simple/sample_tests/too_few.plx
    - t/lib/Test/Simple/sample_tests/too_few_fail.plx
    - t/lib/Test/Simple/sample_tests/two_fail.plx
    - t/lib/TieIn.pm
    - t/lib/TieOut.pm
    - t/pod/emptycmd.t
    - t/pod/emptycmd.xr
    - t/pod/find.t
    - t/pod/for.t
    - t/pod/for.xr
    - t/pod/headings.t
    - t/pod/headings.xr
    - t/pod/include.t
    - t/pod/include.xr
    - t/pod/included.t
    - t/pod/included.xr
    - t/pod/lref.t
    - t/pod/lref.xr
    - t/pod/multiline_items.t
    - t/pod/multiline_items.xr
    - t/pod/nested_items.t
    - t/pod/nested_items.xr
    - t/pod/nested_seqs.t
    - t/pod/nested_seqs.xr
    - t/pod/oneline_cmds.t
    - t/pod/oneline_cmds.xr
    - t/pod/p2u_data.pl
    - t/pod/pod2usage.t
    - t/pod/pod2usage.xr
    - t/pod/pod2usage2.t
    - t/pod/podchkenc.t
    - t/pod/podchkenc.xr
    - t/pod/poderrs.t
    - t/pod/poderrs.xr
    - t/pod/podselect.t
    - t/pod/podselect.xr
    - t/pod/special_seqs.t
    - t/pod/special_seqs.xr
    - t/pod/testcmp.pl
    - t/pod/testp2pt.pl
    - t/pod/testpchk.pl
    - t/pod/testpods/lib/Pod/Stuff.pm
    - t/pod/twice.t
    - t/pod/usage.pod
    - t/pod/usage2.pod

