#!/bin/sh -
#	$OpenBSD: monthly,v 1.6 2005/11/12 16:14:37 jmc Exp $
umask 022

if [ -f /etc/monthly.local ];then
	echo ""
	echo "Running monthly.local:"
	. /etc/monthly.local
else
	echo "Nothing to do!"
fi
