#	$OpenBSD: Makefile,v 1.10 2009/02/17 16:40:51 jsing Exp $

SUBDIR+= elf hidden weak dlsym dlopen dlclose lazy
#SUBDIR+= constructor 
SUBDIR+= link-order edgecases initfirst

install:

.include <bsd.subdir.mk>
