#	$OpenBSD: Makefile,v 1.3 1996/10/30 22:40:49 niklas Exp $
#	$NetBSD: Makefile,v 1.2 1996/11/06 23:09:13 cgd Exp $

.PATH:	${.CURDIR}/..

PROG=	installboot
BINDIR=	/usr/mdec

MAN=	installboot.8
MANSUBDIR=/alpha

CFLAGS+= -g

.include <bsd.prog.mk>
