#	$OpenBSD: Makefile,v 1.14 1997/09/15 06:20:54 downsj Exp $
#	$NetBSD: Makefile,v 1.23 1997/02/04 03:51:37 thorpej Exp $

SUBDIR=	libsa libsaz libkern libz common mkboot uboot installboot

.include <bsd.subdir.mk>
