#	$OpenBSD: Makefile,v 1.16 1999/08/16 09:48:16 downsj Exp $
#	$NetBSD: Makefile,v 1.23 1997/02/04 03:51:37 thorpej Exp $

.if ${MACHINE} == "hp300"
SUBDIR=	libsa libsaz libkern libz common mkboot uboot cdboot installboot
.endif

.include <bsd.subdir.mk>
