# $OpenBSD$

LIB=	clangFrontendTool
NOPIC=
NOPROFILE=

CPPFLAGS+=	${CLANG_INCLUDES}

.include <bsd.own.mk>
SRCS=	ExecuteCompilerInvocation.cpp

.PATH:	${.CURDIR}/../../../llvm/tools/clang/lib/FrontendTool

depend:
	# Nothing here so far ...

install:
	# Nothing here so far ...

.include <bsd.lib.mk>
