#	$OpenBSD: Makefile,v 1.13 2002/09/30 18:09:48 miod Exp $

MAN=	apecs.4 asc.4 autoconf.4 cia.4 intro.4 irongate.4 \
	lca.4 le.4 mem.4 scc.4 tcasic.4 tga.4 tsc.4 tsp.4
MLINKS=	mem.4 kmem.4
MANSUBDIR=alpha

.include <bsd.prog.mk>
