# $OpenBSD: Makefile,v 1.1 2016/07/30 10:56:13 schwarze Exp $

SUBDIR +=	binedit dbm_dump makeinodes run

obj-clean: _SUBDIRUSE

.PHONY: obj-clean

ascii utf8 html lint:

ascii-clean utf8-clean html-clean tman-clean lint-clean:

groff groff-clean html-out html-out-clean lint-out lint-out-clean:

.include <bsd.subdir.mk>
