# $OpenBSD: Makefile,v 1.2 2016/09/04 11:13:08 schwarze Exp $

SUBDIR +=	binedit dbm_dump makeinodes run

obj-clean: _SUBDIRUSE

.PHONY: obj-clean

ascii utf8 html markdown tman lint:

ascii-clean utf8-clean html-clean markdown-clean tman-clean lint-clean:

groff html-out markdown-out lint-out:

groff-clean html-out-clean markdown-out-clean lint-out-clean:

.include <bsd.subdir.mk>
