#	$OpenBSD: Makefile,v 1.8 2004/01/12 18:16:50 millert Exp $

SUBDIR= build

.if make(install)
SUBDIR+= docs/USD.doc/vi.ref docs/USD.doc/vitut
#SUBDIR+= docs/USD.doc/edit docs/USD.doc/exref docs/USD.doc/vitut
.endif

.include <bsd.subdir.mk>
