#	$OpenBSD: Makefile,v 1.11 2004/01/30 23:14:25 jmc Exp $

SUBDIR= build

.if make(install)
SUBDIR+= docs/USD.doc/edit docs/USD.doc/exref
SUBDIR+= docs/USD.doc/vi.ref docs/USD.doc/vitut
.endif

.include <bsd.subdir.mk>
