#	$OpenBSD: Makefile,v 1.10 2004/01/24 12:32:55 jmc Exp $

SUBDIR= build

.if make(install)
SUBDIR+= docs/USD.doc/exref docs/USD.doc/vi.ref docs/USD.doc/vitut
#SUBDIR+= docs/USD.doc/edit
.endif

.include <bsd.subdir.mk>
