#	$OpenBSD: Makefile,v 1.5 2011/11/22 23:06:48 joshe Exp $

SUBDIR+= sigfpe siginfo_addr fpsig earlysig cansig sigaltstack_fork
SUBDIR+= sig-stop
SUBDIR+= siginfo-fault
SUBDIR+= sigio
SUBDIR+= signal-stress
SUBDIR+= sigpending
SUBDIR+= sigprof
SUBDIR+= sigpthread
SUBDIR+= sigsuspend

install:

.include <bsd.subdir.mk>
