#	$OpenBSD: Makefile,v 1.1 1997/09/07 19:59:06 millert Exp $
#	$NetBSD: Makefile,v 1.13 1996/12/18 16:54:57 christos Exp $

PROG=	rsh
SRCS=	rsh.c

KERBEROS=no

.PATH:	${.CURDIR}/../../../usr.bin/rsh
MAN=
BINMODE=4555
BINOWN=	root

.include <bsd.prog.mk>
