#	$OpenBSD: Makefile,v 1.2 1996/10/04 23:09:50 niklas Exp $
#	$NetBSD: Makefile,v 1.6 1996/09/27 03:23:12 chopps Exp $

PROG=binpatch
MAN=binpatch.8

BINDIR=/sbin
LDFLAGS+=-static

.include <bsd.prog.mk>
