#	$OpenBSD: Makefile,v 1.19 2009/07/27 18:36:06 deraadt Exp $

SUBDIR=	atmel bnx cirruslogic fxp kue neomagic ral rum \
	symbol tigon tht tusb3410 typhoon udl uyap yds zydas

.include <bsd.subdir.mk>
