#	$OpenBSD: Makefile,v 1.7 1995/03/18 15:01:05 cgd Exp $
#	$NetBSD: Makefile,v 1.7 1995/03/18 15:01:05 cgd Exp $

PROG=	shutdown
MAN=	shutdown.8
BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
