#	$OpenBSD: Makefile,v 1.10 2008/05/20 04:33:20 miod Exp $

MAN=	dstrc.4 gbe.4 intro.4 ioc.4 macebus.4 mavb.4 mec.4 mkbc.4
MAN+=	owmac.4 owserial.4 power.4 xbow.4 xbridge.4 xheart.4
MLINKS=	macebus.4 macepcibr.4
MANSUBDIR=sgi

.include <bsd.prog.mk>
