#	$OpenBSD: Makefile,v 1.5 2017/10/08 15:14:17 visa Exp $

MAN=		cacheflush.3 get_fpc_csr.3
MANSUBDIR=	loongson octeon

#.if ${MACHINE_CPU} == "mips64"
#NOPIC=
#SRCS=
#.include <bsd.lib.mk>
#.else
NOPROG=
.include <bsd.prog.mk>
#.endif
