#	$OpenBSD: Makefile,v 1.1 2009/09/27 18:20:13 miod Exp $

MAN=		cacheflush.3
MANSUBDIR=	loongson sgi

#.if ${MACHINE_CPU} == "mips64"
#NOPIC=
#SRCS=
#.include <bsd.lib.mk>
#.else
NOPROG=
.include <bsd.prog.mk>
#.endif
