#	$OpenBSD: Makefile,v 1.2 2010/02/03 20:49:00 miod Exp $

MAN=		cacheflush.3 get_fpc_csr.3
MLINKS=		get_fpc_csr.3 set_fpc_csr.3
MANSUBDIR=	loongson sgi

#.if ${MACHINE_CPU} == "mips64"
#NOPIC=
#SRCS=
#.include <bsd.lib.mk>
#.else
NOPROG=
.include <bsd.prog.mk>
#.endif
