#	$OpenBSD: Makefile,v 1.6 2003/07/02 22:44:11 deraadt Exp $

PROG=	spamdb
SRCS=	spamdb.c
MAN=	spamdb.8

CFLAGS+= -Wall -Wstrict-prototypes -ansi -I ${.CURDIR}/../../libexec/spamd

.include <bsd.prog.mk>
