#	$OpenBSD$
PROG=		htpasswd
SRCS=		htpasswd.c
MAN=		htpasswd.1

CFLAGS+=	-g -W -Wall -Werror
CFLAGS+=	-Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations
CFLAGS+=	-Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare

.include <bsd.prog.mk>
