#	$OpenBSD: Makefile,v 1.4 1997/07/20 10:32:44 provos Exp $

PROG= ipsecadm
SRCS= ipsecadm.c kernel.c xf_esp_new.c xf_esp_old.c xf_ah_old.c xf_ah_new.c \
	xf_delspi.c xf_grp.c
NOMAN=

.include <bsd.prog.mk>
