#	$OpenBSD: Makefile,v 1.2 1996/06/26 05:33:07 deraadt Exp $

PROG=	find
SRCS=	find.c function.c ls.c main.c misc.c operator.c option.c stat_flags.c
.PATH:  ${.CURDIR}/../../bin/ls

.include <bsd.prog.mk>
