#	$OpenBSD: Makefile,v 1.6 1995/09/02 05:45:13 jtc Exp $
#	$NetBSD: Makefile,v 1.6 1995/09/02 05:45:13 jtc Exp $

PROG=	cksum
SRCS=	cksum.c crc.c print.c sum1.c sum2.c
LINKS=	${BINDIR}/cksum ${BINDIR}/sum
MLINKS=	cksum.1 sum.1

.include <bsd.prog.mk>
