#	$OpenBSD: Makefile,v 1.45 2002/06/15 18:19:36 provos Exp $
#	$NetBSD: Makefile,v 1.20.4.1 1996/06/14 17:22:38 cgd Exp $

SUBDIR=	csu libarch libc libc_r libcom_err libcompat libcurses libcurses++ \
	libdes libedit libevent libform libkeynote libkvm libl libm libmenu \
	libocurses libossaudio libpanel libpcap libresolv librpcsvc libskey \
	libsectok libssl libtelnet libusbhid libutil libwrap liby libz

.include <bsd.subdir.mk>
