#	$OpenBSD: Makefile,v 1.6 2014/03/02 18:46:16 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
DISKTYPE=rdrootb
FLOPPYSIZE=7936
FLOPPYTYPE=mini34
XNAME=miniroot
LBA=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
