#	$OpenBSD: Makefile,v 1.5 2007/08/09 12:48:07 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=6976
FLOPPYTYPE=mini34
XNAME=miniroot
LBA=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
