#	$OpenBSD: Makefile,v 1.1 2002/04/22 02:40:03 deraadt Exp $

.PATH: ${.CURDIR}/../ramdiskA
BOOT=${DESTDIR}/usr/mdec/fdboot
RAMDISK=RAMDISK
NOBSDRD=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
