#	$OpenBSD: Makefile,v 1.3 2016/09/03 10:56:58 bluhm Exp $
#	$EOM: Makefile,v 1.3 1999/02/25 15:14:24 niklas Exp $

# Test HMAC:

PROG=		hmactest
SRCS=		hash.c hmactest.c conf.c log.c monitor.c util.c

.include <bsd.regress.mk>
