# $OpenBSD: Makefile,v 1.2 2020/04/06 09:55:50 schwarze Exp $

REGRESS_TARGETS = column implicit list warn
TAG_TARGETS	= column implicit list warn
LINT_TARGETS	= warn
HTML_TARGETS	= column implicit list warn

SKIP_TMAN	= column

.include <bsd.regress.mk>
