# $OpenBSD: Makefile,v 1.1 2020/03/13 00:31:06 schwarze Exp $

REGRESS_TARGETS = column list warn
TAG_TARGETS	= column list warn
LINT_TARGETS	= warn
HTML_TARGETS	= column list warn

SKIP_TMAN	= column

.include <bsd.regress.mk>
