# $OpenBSD: Makefile.bsd-wrapper,v 1.2 1999/09/14 14:16:06 espie Exp $

.if ${MACHINE}=="amiga"
all: loadbsd

loadbsd: loadbsd.gz
	zcat ${.ALLSRC} >$@

loadbsd.gz: loadbsd.gz.uu
	uudecode ${.ALLSRC}

CLEANFILES=loadbsd loadbsd.gz
.else
NOPROG=Yes
.endif

MAN=loadbsd.8
MANSUBDIR=/amiga

.include <bsd.prog.mk>
