#	$OpenBSD: Makefile,v 1.1 2015/01/12 17:10:37 deraadt Exp $

.PATH: ${.CURDIR}/../ramdiskA
BOOT=		${DESTDIR}/usr/mdec/fdboot
RAMDISK=RAMDISK
NOBSDRD=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
