#	$OpenBSD: Makefile,v 1.19 2016/03/01 16:22:11 schwarze Exp $

SUBDIR+=	csu
SUBDIR+=	libc
SUBDIR+=	libcrypto
SUBDIR+=	libedit
SUBDIR+=	libevent
SUBDIR+=	libexpat
SUBDIR+=	libfuse
SUBDIR+=	libm
SUBDIR+=	libpthread
SUBDIR+=	libradius
SUBDIR+=	libskey
SUBDIR+=	libsndio
SUBDIR+=	libssl
SUBDIR+=	libtls
SUBDIR+=	libutil

install:

.include <bsd.subdir.mk>
