# $OpenBSD: Makefile,v 1.5 2015/02/06 09:38:22 schwarze Exp $

REGRESS_TARGETS	 = badargs-man badargs-mdoc fill-man
REGRESS_TARGETS	+= negative scaling-man scaling-mdoc
LINT_TARGETS	 = badargs-man
HTML_TARGETS	 = fill-man

.include <bsd.regress.mk>
