#	$OpenBSD: Makefile,v 1.4 1996/08/17 04:45:39 deraadt Exp $
#
#	@(#)Makefile	8.1 (Berkeley) 6/6/93

PROG=	locate.code
CFLAGS+= -I${.CURDIR}/../locate 
NOMAN=	noman
BINDIR=	${LIBEXECDIR}

.include "../Makefile.inc"
.include <bsd.prog.mk>
