#	$OpenBSD: Makefile,v 1.12 2005/05/28 04:43:19 marius Exp $
#	$NetBSD: Makefile,v 1.1 1997/12/30 23:27:11 cgd Exp $

SUBDIR+= basename bc dc diff diff3 dirname grep gzsig m4 make patch 
SUBDIR+= sort ssh tsort

.include <bsd.subdir.mk>
