#	$OpenBSD: Makefile,v 1.1.2.1 1996/12/03 13:17:05 mickey Exp $

PROG=	installboot
CFLAGS+=-DDEBUG -g -Wall
MAN=	installboot.8

# Need this to work in the miniroot
LDSTATIC=	-static

.include <bsd.prog.mk>
