#	$OpenBSD: Makefile,v 1.3 1996/06/23 14:32:03 deraadt Exp $
#	$NetBSD: Makefile,v 1.6 1996/04/05 04:17:57 cgd Exp $

PROG=	quotacheck
SRCS=	quotacheck.c preen.c fsutil.c
MAN=	quotacheck.8
.PATH:	${.CURDIR}/../fsck

.include <bsd.prog.mk>
