#	$OpenBSD: Makefile,v 1.6 1996/04/05 04:17:57 cgd Exp $
#	$NetBSD: Makefile,v 1.6 1996/04/05 04:17:57 cgd Exp $

PROG=	quotacheck
SRCS=	quotacheck.c preen.c
MAN=	quotacheck.8
.PATH:	${.CURDIR}/../fsck_ffs

.include <bsd.prog.mk>
