# $OpenBSD: Makefile,v 1.2 2014/11/21 01:52:45 schwarze Exp $

REGRESS_TARGETS	 = dupe late long missing
LINT_TARGETS	 = dupe late missing
MARKDOWN_TARGETS = dupe late long missing

SKIP_GROFF	 = long

.include <bsd.regress.mk>
