# $OpenBSD: Makefile,v 1.2 2017/07/09 15:28:34 espie Exp $

LIB=	LLVMBitWriter
NOPROFILE=

SRCS+=	BitWriter.cpp \
	BitcodeWriter.cpp \
	BitcodeWriterPass.cpp \
	ValueEnumerator.cpp

.PATH:	${.CURDIR}/../../../llvm/lib/Bitcode/Writer
