#	$OpenBSD: Makefile,v 1.5 1995/03/18 14:55:18 cgd Exp $
#	$NetBSD: Makefile,v 1.5 1995/03/18 14:55:18 cgd Exp $

PROG=	dumplfs
SRCS=	dumplfs.c lfs_cksum.c misc.c
.PATH:	${.CURDIR}/../../sys/ufs/lfs
MAN=	dumplfs.8

.include <bsd.prog.mk>
