# $OpenBSD: Makefile,v 1.16 2011/11/17 16:28:45 schwarze Exp $

SUBDIR+= Ad Ap Aq Ar At Bd Bk Bl Brq Bx Cd Dq Dv Er Ev Fl Fo Ic In
SUBDIR+= Lb Li Ms Mt Nd Nm No Ns Op Ox Pf Pp Qq Rs Sm Sq St Sx Sy Tn Ux Vt Xr
SUBDIR+= blank

# disabled, mandoc must be fixed:
# Pa

ascii groff groff-clean obj-clean tman: _SUBDIRUSE

.include <bsd.subdir.mk>
