# $OpenBSD: Makefile,v 1.11 2011/01/30 18:28:02 schwarze Exp $

SUBDIR+= Ad Ar At Bd Bk Bl Bx Cd Er Fl Fo Ic In
SUBDIR+= Lb Li Ms Mt Nd Nm Op Rs Sm St Sx Sy Tn Vt Xr
SUBDIR+= blank

# disabled, mandoc must be fixed:
# Pa

groff groff-clean: _SUBDIRUSE

.include <bsd.subdir.mk>
