# $OpenBSD: Makefile,v 1.7 2010/04/12 23:02:03 schwarze Exp $

SUBDIR+= Ar Bd Bl Fl Fo In Li Op Rs Sm Xr
SUBDIR+= blank

# disabled, mandoc must be fixed:
# Pa

groff groff-clean: _SUBDIRUSE

.include <bsd.subdir.mk>
