#	$OpenBSD: Makefile,v 1.3 1997/07/15 07:23:53 downsj Exp $

PROG=	makemap
MAN=	makemap.8
ENVDEF+=-DNOT_SENDMAIL

WANT_LIBSMDB=1
WANT_LIBSMUTIL=1

.include "../../Makefile.inc"
.include <bsd.prog.mk>
