#	$OpenBSD: Makefile,v 1.2 1994/11/14 20:27:21 jtc Exp $
#	$NetBSD: Makefile,v 1.2 1994/11/14 20:27:21 jtc Exp $

PROG=	chflags
SRCS=	chflags.c stat_flags.c
.PATH:	${.CURDIR}/../../bin/ls

.include <bsd.prog.mk>
