#	$OpenBSD: Makefile,v 1.7 2019/09/02 22:23:11 bluhm Exp $

SUBDIR +=	arp autoport
SUBDIR +=	broadcast_bind
SUBDIR +=	carp
SUBDIR +=	frag
SUBDIR +=	in_pcbbind ipsec
SUBDIR +=	mcast
SUBDIR +=	pmtu
SUBDIR +=	recvmsg
SUBDIR +=	sendsrcaddr

.include <bsd.subdir.mk>
