# $OpenBSD: Makefile,v 1.25 2018/08/23 14:16:12 schwarze Exp $

SUBDIR  = args cond esc scale string
SUBDIR += br cc de ds ft ig it ll na nr po ps
SUBDIR += return rm rn shift sp ta ti tr while

.include "../Makefile.sub"
.include <bsd.subdir.mk>
