# $OpenBSD: Makefile,v 1.11 2012/07/07 18:27:36 schwarze Exp $

SUBDIR  = args cond esc string
SUBDIR += br cc de ds na ps rm sp

ascii groff groff-clean obj-clean tman: _SUBDIRUSE

.include <bsd.subdir.mk>
