#	$OpenBSD: Makefile,v 1.3 1996/11/14 15:04:50 mickey Exp $

PROG=	elf2olf
CPPFLAGS+= -DOS_ID=OOS_OPENBSD
LINKS=	${BINDIR}/elf2olf ${BINDIR}/olf2olf
MLINKS=	elf2olf.1 olf2elf.1

.include <bsd.prog.mk>
