# $OpenBSD: Makefile,v 1.6 2019/02/21 23:06:33 bluhm Exp $

SUBDIR =	libressl openssl openssl11

# the above binaries must have been built before we can continue
#SUBDIR +=	cert
SUBDIR +=	cipher
SUBDIR +=	netcat
SUBDIR +=	session

.include <bsd.subdir.mk>
