#	$OpenBSD: Makefile,v 1.8 1995/03/18 14:54:45 cgd Exp $
#	$NetBSD: Makefile,v 1.8 1995/03/18 14:54:45 cgd Exp $

PROG=	dmesg
MAN=	dmesg.8
BINGRP=	kmem
BINMODE=2555
LDADD=	-lkvm
DPADD=	${LIBKVM}

.include <bsd.prog.mk>
