#	$OpenBSD: Makefile.bsd-wrapper,v 1.3 2000/08/25 14:36:38 maja Exp $

SUBDIR+= libiberty libio libf2c libobjc

.if (${MACHINE_ARCH} != "sparc64")
SUBDIR+= libstdc++
.endif

# just so that the main directory will have a subdir, which simplifies
# libf2c/libobjc build 
obj: _SUBDIRUSE
	cd $(.CURDIR) && $(MAKE) -f Makefile.bsd-wrapper1 obj
	cd $(.CURDIR)/gcc && $(MAKE) -f Makefile.bsd-wrapper obj

.include <bsd.subdir.mk>
