#	$OpenBSD: Makefile.bsd-wrapper,v 1.2 1996/09/26 14:16:13 deraadt Exp $

.if (${MACHINE_ARCH} == "mips")
MAKE+= -DNOPIC
.endif


SUBDIR+= libiberty libio libstdc++ libf2c libobjc

# just so that the main directory will have a subdir, which simplifies
# libf2c/libobjc build 
obj: _SUBDIRUSE
	cd $(.CURDIR) && $(MAKE) -f Makefile.bsd-wrapper1 obj

.include <bsd.subdir.mk>
