#	$OpenBSD: Makefile,v 1.2 2006/03/09 19:14:10 millert Exp $

PROG=	login_reject
SRCS=	login_reject.c
MAN=	login_reject.8
CFLAGS+=-Wall

BINOWN=	root
BINGRP=	auth
BINMODE=555
BINDIR= /usr/libexec/auth

.include <bsd.prog.mk>
