# $OpenBSD: Makefile,v 1.3 2019/03/05 09:44:40 jsg Exp $

LIB=	LLVMRemarks
NOPROFILE=

SRCS+=	BitstreamRemarkParser.cpp \
	BitstreamRemarkSerializer.cpp \
	Remark.cpp \
	RemarkFormat.cpp \
	RemarkLinker.cpp \
	RemarkParser.cpp \
	RemarkSerializer.cpp \
	RemarkStringTable.cpp \
	YAMLRemarkParser.cpp \
	YAMLRemarkSerializer.cpp

.PATH:	${.CURDIR}/../../../llvm/llvm/lib/Remarks
