#	$OpenBSD: Makefile,v 1.4 2014/09/18 13:46:54 syl Exp $

MAN=	cpsw.4 dmtimer.4 edma.4 gptimer.4 imx.4 imxenet.4 imxesdhc.4 \
	imxiic.4 intc.4 intro.4 omap.4 omdog.4 omgpio.4 ommmc.4 prcm.4 \
	sitaracm.4

MANSUBDIR=armv7

.include <bsd.prog.mk>
