#	$OpenBSD: Makefile,v 1.2 1996/06/26 05:38:34 deraadt Exp $

PROG=	rpcgen
SRCS=	rpc_clntout.c rpc_cout.c rpc_hout.c rpc_main.c rpc_parse.c rpc_scan.c \
	rpc_svcout.c rpc_util.c rpc_sample.c rpc_tblout.c

CFLAGS += -ansi

.include <bsd.prog.mk>
