# $OpenBSD: Makefile,v 1.4 2017/03/05 19:59:26 schwarze Exp $

REGRESS_TARGETS = link noarg font
LINT_TARGETS	= noarg

# it's unclear what font changes in link destinations should do

SKIP_MARKDOWN  ?= font

.include <bsd.regress.mk>
