# $OpenBSD: Makefile,v 1.2 1996/10/04 22:35:34 niklas Exp $
# $NetBSD: Makefile,v 1.5 1996/09/27 03:23:13 chopps Exp $

PROG=loadkmap
NOMAN=loadkmap
BINDIR=/usr/sbin
SUBDIR=din sw us

.include <bsd.prog.mk>
