# $OpenBSD: Makefile,v 1.8 2014/08/18 16:26:13 schwarze Exp $

REGRESS_TARGETS	 = breaking broken empty literal lonelyRE
REGRESS_TARGETS	+= nested noRE REarg width
LINT_TARGETS	 = lonelyRE noRE REarg

.include <bsd.regress.mk>
