# $OpenBSD: Makefile,v 1.13 2019/01/05 20:00:33 schwarze Exp $

REGRESS_TARGETS	 = an-margin breaking broken empty literal lonelyRE
REGRESS_TARGETS	+= nested noRE nowidth paragraph REarg width
LINT_TARGETS	 = empty lonelyRE noRE REarg
HTML_TARGETS	 = literal paragraph

.include <bsd.regress.mk>
