# $OpenBSD: Makefile,v 1.3 2011/01/01 21:14:09 schwarze Exp $

REGRESS_TARGETS=escape infinite zerolength name
GROFF_TARGETS=escape zerolength name

# The infinite test fails badly with groff-1.20.1:
# It fails to print the following text.

.include <bsd.regress.mk>
