#	$OpenBSD: Makefile,v 1.3 2016/09/03 10:56:58 bluhm Exp $
#	$EOM: Makefile,v 1.6 2000/03/28 21:22:07 ho Exp $

# Test PRF:

PROG=		prftest
SRCS=		prf.c hash.c log.c prftest.c conf.c monitor.c util.c

.include <bsd.regress.mk>
