# $OpenBSD: Makefile,v 1.6 2017/03/05 19:59:26 schwarze Exp $

REGRESS_TARGETS = simple font

# it's unclear what font changes in link destinations should do

SKIP_MARKDOWN ?= font

.include <bsd.regress.mk>
