# $OpenBSD: Makefile,v 1.11 2014/10/28 02:49:48 schwarze Exp $

REGRESS_TARGETS  = leading-mdoc leading-man multiple trailing-mdoc zerowidth
REGRESS_TARGETS += eos eos-man break nobreak
REGRESS_TARGETS += tab tab-man esct-mdoc esct-man

UTF8_TARGETS	 = zerowidth

HTML_TARGETS	 = zerowidth

LINT_TARGETS	 = trailing-mdoc tab tab-man esct-mdoc esct-man

.include <bsd.regress.mk>
