#	$OpenBSD: Makefile,v 1.1 2003/04/14 14:35:04 millert Exp $

PROG=	disknames
SRCS=	disknames.c
CFLAGS=	-Os ${PIPE} ${DEBUG} -I${.CURDIR}
MAN=

.PATH:	${.CURDIR}/../../../distrib/special/disknames

.include <bsd.prog.mk>
