#	$OpenBSD: Makefile,v 1.1 2007/04/18 10:18:23 otto Exp $
#
# Regress tests for newfs

REGRESS_TARGETS =	run-regress-checknewfs

run-regress-checknewfs:
	sh ${.CURDIR}/checknewfs

.include <bsd.regress.mk>
