#	$OpenBSD: Makefile,v 1.5 2000/12/28 21:21:25 smurph Exp $
#.if ${MACHINE} == "mvmeppc"

SUBDIR=  bugcrt libbug libsa libz bootsd bootxx bootst tftpboot
#sboot XXX future
#.endif

SUBDIR+=installboot

.include <bsd.subdir.mk>
