# $OpenBSD$

LIB=	LLVMMIRParser
NOPIC=
NOPROFILE=

.include <bsd.own.mk>
SRCS=	MILexer.cpp \
	MIParser.cpp \
	MIRParser.cpp

.PATH:	${.CURDIR}/../../../llvm/lib/CodeGen/MIRParser

depend:
	# Nothing here so far ...

install:
	# Nothing here so far ...

.include <bsd.lib.mk>
