# $OpenBSD$

LIB=	LLVMFrontendHLSL
NOPROFILE=

CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/Frontend
CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/Frontend/HLSL

SRCS+=	HLSLResource.cpp

.PATH:	${.CURDIR}/../../../llvm/llvm/lib/Frontend/HLSL
