#	$OpenBSD: Makefile,v 1.2 2007/05/19 15:52:31 millert Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=5760
FLOPPYTYPE=floppy288
XNAME=cdrom
NOFS=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
