#	$OpenBSD: Makefile,v 1.3 2007/08/09 12:48:07 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=11520
FLOPPYTYPE=floppy576
XNAME=cdrom
NOFS=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local
