#	$OpenBSD: Makefile,v 1.5 2010/10/18 04:07:50 deraadt Exp $

.PATH: ${.CURDIR}/../ramdisk
RAMDISK=RAMDISK_CD
FLOPPYSIZE=6976
FLOPPYTYPE=mini34
XNAME=miniroot
LBA=1

.include "${.CURDIR}/../common/Makefile.inc"

LISTS+=		${.CURDIR}/list.local

