#	$OpenBSD: Makefile,v 1.3 1995/09/06 21:36:37 jtc Exp $
#	$NetBSD: Makefile,v 1.3 1995/09/06 21:36:37 jtc Exp $

MAN=	MAKEDEV.8 boot_mac68k.8
MLINKS=	MAKEDEV.8 makedev.8
MANSUBDIR=/mac68k

.include <bsd.prog.mk>
