#	$OpenBSD: Makefile,v 1.3 2012/08/21 14:46:18 pascal Exp $
#	$NetBSD: Makefile,v 1.2 1997/05/14 07:57:13 thorpej Exp $

PROG=	mkboot
NOMAN=
NOPIE=

CFLAGS+=	-I${.CURDIR}/../include
CPPFLAGS=

install:

.include <bsd.prog.mk>
