#	$OpenBSD: Makefile,v 1.1 1997/07/14 08:14:52 downsj Exp $
#	$NetBSD: Makefile,v 1.2 1997/05/14 07:57:13 thorpej Exp $

PROG=	mkboot
NOMAN=

.include "${.CURDIR}/../Makefile.inc"

CFLAGS+=	-I${.CURDIR}/../include

install:

.include <bsd.prog.mk>
