#	$OpenBSD: Makefile,v 1.5 2019/09/05 02:35:46 bluhm Exp $

SUBDIR +=	autoport
SUBDIR +=	frag6
SUBDIR +=	mcast6
SUBDIR +=	nd6
SUBDIR +=	pktinfo_addr
SUBDIR +=	recvmsg rh0 rip6cksum
SUBDIR +=	srcaddr

.include <bsd.subdir.mk>
