#	$OpenBSD: Makefile,v 1.3 1997/09/21 11:51:32 deraadt Exp $

PROG=	unifdef
COPTS+=	-Wall -Werror
#MLINKS= unifdef.1 unifdefall.1

#beforeinstall:
#	${INSTALL} ${INSTALL_COPY} -o ${BINOWN} -g ${BINGRP} -m ${BINMODE} \
#		${.CURDIR}/unifdefall.sh ${DESTDIR}${BINDIR}/unifdefall

.include <bsd.prog.mk>
