#	$OpenBSD: Makefile,v 1.19 2009/04/19 00:59:39 deraadt Exp $

SUBDIR=	libstubs \
	ccdconfig dd dhclient dmesg ftp grep gzip ifconfig init \
	kbd less more newfs pppd rsh sha256 sysctl

install:

.include <bsd.subdir.mk>
