#	$OpenBSD: Makefile,v 1.23 2011/09/17 14:05:27 haesbaert Exp $

SUBDIR=	libstubs \
	date dd dhclient dmesg ed ftp grep gzip ifconfig init \
	kbd less more mt newfs ping restore sha256 sysctl 

install:

.include <bsd.subdir.mk>
