#	$OpenBSD: Makefile,v 1.20 2009/04/19 03:33:19 deraadt Exp $

SUBDIR=	libstubs \
	ccdconfig dd dhclient dmesg ed ftp grep gzip ifconfig init \
	kbd less more mt newfs pppd restore rsh sha256 sysctl

install:

.include <bsd.subdir.mk>
