#! /usr/bin/perl
# $OpenBSD$
# Written by Marc Espie
# Public domain

use Test::Simple tests => 1;
use OpenBSD::PackageName;

my @list=qw(py-MxDateTime-2.0.1-py2.1);

ok(OpenBSD::PackageName::pkgspec_match('py-MxDateTime->=2.0-py2.1', @list) == 1);
