#! /usr/bin/perl

# $OpenBSD: inject-temp1,v 1.1 2019/07/09 13:49:47 espie Exp $
use strict;
use warnings;
use OpenBSD::Temp;

package OpenBSD::Temp;
use Wrapper;
wrap('permanent_file',
    sub {
    	my $original = shift;
	if (!defined $_[0]) {
		shift;
		unshift @_, '/nonexistent';
	}
	goto &$original;
    });
1;
