#! /usr/bin/perl

# $OpenBSD$
#use OpenBSD::Temp;
use strict;
use warnings;
use OpenBSD::Temp;

package OpenBSD::Temp;
use Wrapper;

wrap('permanent_dir', 
    sub {
	my $original = shift;
	$_[0] = "/nonexistent";
	goto &$original;
    });
1;
