#! /usr/bin/perl

# $OpenBSD: inject-temp1,v 1.2 2019/07/10 11:55:40 espie Exp $
use strict;
use warnings;

use OpenBSD::md5;

package OpenBSD::digest;
use Wrapper;

wrap('digest_file',
    sub {
	my $original = shift;
    	if ($_[1] =~ m,/a$,) {
		my $self = shift;
		my $d = $self->algo;
		$d->addfile("/dev/null");
		return $d->digest;
	} else {
		goto &$original;
	}
    });

1;
