#	$OpenBSD: Makefile,v 1.7 2002/03/12 15:19:28 art Exp $

SUBDIR=rfcfdg rfnowait rfsharefd kqueue

# RFMEM requires something like rfork_thread() to fix up the stack
#SUBDIR=rfmem madness rfmem-stack

install:

.include <bsd.subdir.mk>
