---
abstract: 'Perl termcap interface'
author:
  - 'Jonathan Stowe <jns@gellyfish.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.66, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Term-Cap
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0.33'
resources:
  repository: https://github.com/jonathanstowe/Term-Cap.git
version: '1.18'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
