#	$OpenBSD: Makefile.inc,v 1.1 2004/01/20 04:20:58 drahn Exp $

CRUNCHGENOPTS= -E

#	$OpenBSD: Makefile.inc,v 1.1 2004/01/20 04:20:58 drahn Exp $

CRUNCHGENOPTS= -E

#	$OpenBSD: Makefile.inc,v 1.1 2001/09/01 16:47:03 drahn Exp $

CRUNCHGENOPTS= -E

