#	$OpenBSD: Makefile,v 1.1 2003/08/07 19:22:38 miod Exp $

# TODO: cl clock dart memc nvram sclock syscon vx
MAN=	autoconf.4 bussw.4 ie.4 intro.4 mem.4 pcctwo.4 ssh.4 ve.4 vme.4 vs.4
MANSUBDIR=mvme88k

.include <bsd.prog.mk>
