# $OpenBSD: Makefile,v 1.7 2014/06/20 18:32:51 schwarze Exp $

REGRESS_TARGETS = empty font emptyNAME emptyNAMEuse badNAME badNAMEuse long

LINT_TARGETS = badNAME badNAMEuse

SKIP_GROFF = emptyNAMEuse badNAMEuse

.include <bsd.regress.mk>
