# $OpenBSD: Makefile,v 1.4 2012/07/09 17:52:09 schwarze Exp $

REGRESS_TARGETS = empty font emptyNAME emptyNAMEuse badNAME badNAMEuse

SKIP_GROFF = emptyNAME emptyNAMEuse badNAME badNAMEuse

.include <bsd.regress.mk>
